# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "0.29.1"
  compile-option = ""
  compile-target-macros = []
  description = "nothing here"
  link-option = ""
  name = "macro_calling"
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[target.x86_64-w64-mingw32]
  compile-macros-for-target = "all"

[target.x86_64-linux-ohos]
  compile-option = "-B=${OHOS_ROOT}/llvm/prebuilt/x86_64-linux-ohos/bin --sysroot=${OHOS_ROOT}/llvm/prebuilt/x86_64-linux-ohos/sysroot"
  compile-macros-for-target = "all"

[target.aarch64-linux-ohos]
  compile-option = "-B${OHOS_ROOT}/out/generic_generic_arm_64only/hisi_all_phone_standard/obj/third_party/musl/usr/lib/aarch64-linux-ohos -B${OHOS_ROOT}/prebuilts/clang/ohos/windows-x86_64/llvm/bin -L${OHOS_ROOT}/prebuilts/clang/ohos/windows-x86_64/llvm/lib/clang/15.0.4/lib/aarch64-linux-ohos -L${OHOS_ROOT}/prebuilts/clang/ohos/windows-x86_64/llvm/lib/aarch64-linux-ohos -L${OHOS_ROOT}/out/generic_generic_arm_64only/hisi_all_phone_standard/obj/third_party/musl/usr/lib/aarch64-linux-ohos -L${OHOS_ROOT}/out/generic_generic_arm_64only/hisi_all_phone_standard/thirdparty/openssl"
	compile-macros-for-target = "all"

[target.aarch64-linux-android26]
  compile-option = "-B=${OHOS_ROOT}/llvm/prebuilt/darwin-arm64/bin --sysroot=${OHOS_ROOT}/llvm/prebuilt/darwin-arm64/sysroot"
  compile-macros-for-target = "all"
[target.aarch64-linux-android31]
  compile-option = "-B=${OHOS_ROOT}/llvm/prebuilt/darwin-arm64/bin --sysroot=${OHOS_ROOT}/llvm/prebuilt/darwin-arm64/sysroot"
  compile-macros-for-target = "all"
[target.aarch64-linux-android32]
  compile-option = "-B=${OHOS_ROOT}/llvm/prebuilt/darwin-arm64/bin --sysroot=${OHOS_ROOT}/llvm/prebuilt/darwin-arm64/sysroot"
  compile-macros-for-target = "all"
[target.aarch64-linux-android35]
  compile-option = "-B=${OHOS_ROOT}/llvm/prebuilt/darwin-arm64/bin --sysroot=${OHOS_ROOT}/llvm/prebuilt/darwin-arm64/sysroot"
  compile-macros-for-target = "all"