# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.
 
[[packages]]
filters = { include = ["NS.+"] }
package-name = "objc.foundation"

[[packages]]
filters = { include = ["test1", "test2", "test3"] }
package-name = "cjworld"
output-path = "."

[output-roots.default]
path = "mirrors"

[sources.all]
paths = ["test.h"]

[sources-mixins.default]
sources = [".*"]
arguments-append = [
    "-F", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks",
    "-isystem", "/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include",
    "-isystem", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include",
    "-DTARGET_OS_IPHONE"
]
