/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 * 
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

// LEVEL: 0
// DEPENDENCE: StrInterPolationContent_01.cj
// (CJNATIVE and not OHOS and not iOS) EXEC: %compiler %import-cangjie-stdx %cmp_opt %f -o %output %cmp_utest_opt
// (CJNATIVE and not OHOS and not iOS) RUN-EXEC: %run_stdx %output %run_utest_opt %run_args

import stdx.syntax.*

@Test
func test_StrInterpolationContent_01() {
    let res = parseFile("./StrInterPolationContent_01.cj")
    var diags = res.diags
    @Assert(diags.size, 0)

    let sourcefile: SourceFile = res.node.getOrThrow()
    @Assert(sourcefile.toString().contains(##"var a: Int64 = 1
var _a: String = "cangjie: ${a}""##))

    var varDecl: VarDecl = (sourcefile.topLevelDecls[1] as VarDecl).getOrThrow()
    var expr: LitConstStrExpr = (varDecl.initializer.getOrThrow() as LitConstStrExpr).getOrThrow()
    match (expr.strPartExprs[1]) {
        case StrInterpolation(strIPC) =>
            @Assert(strIPC.toString(), ##"${a}"##)
            @Assert(strIPC.toTokens().toString(), ##"${ a }"##)
            @Assert(strIPC.interpolationBlock.toString(), ##"{a}"##)
        case _ => @Assert(false)
    }
}
