# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "cmp"
  output-type = "dynamic"
  override-compile-option = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[source-set.common]
  src-dir = "./common"

[source-set.platformA]
  src-dir = "./platformA"
  condition = ["feature.arch.big"]

[source-set.platformB]
  src-dir = "./platformB"
  condition = ["feature.arch.little"]
