// DEPENDENCE: ../expect/%n.expect
// EXEC-1: %compiler %cmp_opt %f -o %output 2>%f.txt
// EXEC: %diff %n.expect %f.txt

main():Unit{
    let a = '
    c
    let b = '
    c
}
// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.
