// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package pkg

public const ENCODING = "utf-8"

public class A1 {
    public static const ID: String = "1"
}

public class A2<T> {
    public static const ID: String = "2"
}

public struct A3<T> {
    public static const ID: String = "3"
}
