# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "0.60.4"
  name = "mp"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  output-type = "dynamic"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]

[source-set.common]
  src-dir = ["./src/common"]

# Linux And windows Have Same Impl
[source-set.windowsorlinux]
  src-dir = ["./src/windows"]
  condition.a = ["feature.os.windows"]
  condition.b = ["feature.os.linux"]
  condition.c = ["feature.os.darwin"]
