/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 * 
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package p

interface i________<x, y, z> where x <: Int32, y <: Int64, z <: Unit{
    
}

interface I1 <X, Y, Z> where X <: Int32, Y <: Int64, Z <: Unit{
    
}

