# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "1.2.0"
  name = "geninst_cross_package"
  organization = ""
  description = "TC-GENINST-CROSS-PACKAGE 跨包扩展/缓存隔离最小工程"
  version = "1.0.0"
  target-dir = ""
  script-dir = ""
  output-type = "executable"
  compile-option = "-Woff=all"
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  pkg_a = { path = "./pkg_a" }
