// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package A

public var varr1: VArray<Int64, $5> = [1, 2, 3, 4, 5]

public class C1 {
    public var varr1: VArray<Int64, $5> = [11, 12, 13, 14, 15]
}

public struct S1 {
    public var varr1: VArray<Int64, $5> = [21, 22, 23, 24, 25]
}
