// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package pkg

public func f1() {
    println("f1")
}

public func f2() {
    println("f2")
}

public func f3() {
    println("f3")
}

public func f4() {
    println("f4")
}

public func f5() {
    println("f5")
}

public func f6() {
    println("f6")
}
