# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[profile]
experimental = true

[package]
  cjc-version = "0.60.4"
  name = "demo"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  [package.package-configuration]

[dependencies]
  [dependencies.mp]
    version = "1.0.0"
    path = "./mp"
