// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package b

internal import aoo.*
internal import coo.*

public func testmain(): Int64 {
    print("hello world\n")
    println(coopp)
    return 0
}