/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 * 
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

// LEVEL: 1
// EXEC: %compiler %cmp_opt %f -o %output
// RUN-EXEC: %run %run_opt %output %run_args

var var_1665279311855_4465 = Class_1665279311855_197()

public open class Class_1665279311855_197 {
    public init() {}
    public init(namedParam_1665279311855_1129!: Int16) {
        func_1665279311855_1229(
            if (true) {
                while (let caseVar_1665279311855_4469 <- var_1665279311855_4465) {
                    ();
                    break
                }
            } else {
                ()
            })
    }
}

func func_1665279311855_1229(param_1665279311855_1230: Unit): Unit { // block id: 1231
}

main(): Int64 {
    Class_1665279311855_197(namedParam_1665279311855_1129: 1)
    return 0;
}
