// Copyright (c) Huawei Technologies Co., Ltd. 2025-2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package myPkgA

// V0
public open class Foo {
    public open func f(): Unit {
    }

    public open func f(x: Bool): Unit {
    }
}

public abstract class Bar {
    public func bar1(): Unit
    public func bar2(): Unit
}

main() {}