# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[profile]
experimental = true

[dependencies]

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "reserved_main"
  output-type = "executable"
  override-compile-option = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[source-set.main]
  src-dir = "./src/main"

[source-set.linux]
  condition = ["feature.os.linux", "feature.os.posix"]
