interface I1 {
    func foo() {}
    func bar(): Unit 
}

let (a1, b1) = (1, 2)
var c = a
let a = 1
class B {
    let a = 1
    var b = 3
}

main() {}

// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.
