/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 * 
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

// LEVEL: 2
// (not CJNATIVE) EXEC: %compiler %f %macro_opt 
// EXEC: %compiler %f %macro_opt 

macro package use

import std.ast.*

public macro Y(input: Tokens): Tokens {
    return quote(@Y[1](1))
}
