# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[profile]
experimental = true

[dependencies]
  cmp = { path = "./cmp", version = "1.0.0" }

[package]
  cjc-version = "0.60.4"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "testing"
  output-type = "executable"
  override-compile-option = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}