/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 * 
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

// LEVEL: 1
//stringFile.cj
let s = "\\"
let s1 = "\\KDvP=sc\"~"
let s2 = "123456789\n"
let s3 = "abcdefghi'"
let s4 = "}"
let s5 = "\t"
let s6 = ###"asdfaf"#"###
let s7 = ##"
Hello,
Cangjie
Lang#"##
let s8 = '''
Hello,
Cangjie\\'''
let s9 = ###"#asdfaf"#"###
