/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 * 
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

/*
  @Structure:    complex-aux
*/

var v51F32: Float32 = InitCommon.initFloat32("E1")
var v52F32: Float32 = InitCommon.initFloat32("E2") + foo4() + foo2()
var v53F32: Float32 = InitCommon.initFloat32("E3")

func foo5(): Float32 {
    5.5
}
