# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.
 
imports = ["test1.toml", "test2.toml"]

[sources.all]
paths = ["test.h"]

[[packages]]
filters = { include = ["M"] }
package-name = "cjworld"
output-path = "."