# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.
[global]
  strict-tls = false
[repository.cache]
  path = "dep_type_03"
  

[repository.home]
  registry = "https://mirror-centralrepo.devcloud.cn-north-4.huaweicloud.com/artifactory/api/cjpm/cangjie-central-cjpm-test/"
  token=CANGJIE_REPO_TOKEN