# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]
boo = {path = "boo"}
coo = {path = "coo"}

[package]
  cjc-version = "1.0.0"
  compile-option = "-Woff=all"
  description = "nothing here"
  link-option = ""
  name = "b"
  output-type = "executable"
  override-compile-option = ""
  version = "1.0.0"
[profile.build]
lto = "full" 
[profile.build.combined]
 b = "dynamic"
[target.x86_64-linux-ohos]
  compile-option = "-B=${OHOS_ROOT}/llvm/prebuilt/x86_64-linux-ohos/bin --sysroot=${OHOS_ROOT}/llvm/prebuilt/x86_64-linux-ohos/sysroot"

[target.aarch64-linux-ohos]
  compile-option = "-B${OHOS_ROOT}/sysroot/usr/lib/aarch64-linux-ohos -B${OHOS_ROOT}/llvm/bin -L${OHOS_ROOT}/llvm/lib/clang/15.0.4/lib/aarch64-linux-ohos -L${OHOS_ROOT}/llvm/lib/aarch64-linux-ohos -L${OHOS_ROOT}/sysroot/usr/lib/aarch64-linux-ohos"
	

[target.aarch64-linux-android26]
  compile-option = "-B=${NDK_ROOT}/bin --sysroot=${NDK_ROOT}/sysroot"
[target.aarch64-linux-android31]
  compile-option = "-B=${NDK_ROOT}/bin --sysroot=${NDK_ROOT}/sysroot"
[target.aarch64-linux-android32]
  compile-option = "-B=${NDK_ROOT}/bin --sysroot=${NDK_ROOT}/sysroot"
[target.aarch64-linux-android35]
  compile-option = "-B=${NDK_ROOT}/bin --sysroot=${NDK_ROOT}/sysroot"

[target.arm-linux-android23]
  compile-option = "-B=${NDK_ROOT}/bin --sysroot=${NDK_ROOT}/sysroot"