// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

class A {
    var mem = 50
}

class cls {
    public static let aaa = 10
    private static let bbb = "HHHH"
    static let ccc = [1, 2, 3]
    public static var ddd = A()
    init() {
        var zzz = 50
    }
}

main() {
    0
}
