# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "testing"
  output-type = "dynamic"
  target-dir = ""
  version = "1.0.0"

[source-set.common]
  src-dir = "./common"

[source-set.linux]
  src-dir = "./linux"
  condition = ["feature.os.linux"]

[profile]
  [profile.build]
    incremental = false
  [profile.customized-option]
    debug = "-g -Woff all -j1"
    release = "-V --fast-math -O2 -s -Woff all"