/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 * 
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

/*
  @Description: Aux file with module 'mod_05_a01'

  @Module:      mod_05_01_01_01_a04

  @Structure:   complex-aux

*/

package pkg

public func f1(): Unit {} 
func f12(): Unit {}         //  can be accessed in the current package. 
