class S{
    open
    public  //Modifier
    mut
    prop size  // Identifier
    :Int64  // Type
    {
        set(a) // param name
        {
            1  // body
        }

        get()
        {
            0  // body
        }
    }
}

main() {
    0
}

// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.
