/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 * 
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

// LEVEL: 1
// EXEC: %compiler %cmp_opt %f -o %output
// RUN-EXEC-PIPE-1: %run %run_opt %output %run_args 2>&1 | compare %f
// ASSERT: regex throwable_50020.cj
// (not O2 ) ASSERT: regex default.*A
// (not O2) ASSERT: scan throwable_50020.cj:22

class A <: Exception {}

class B <: Exception {}

class C {
    public static var a: Int64 = if (true) {
        throw A();
        1
    } else {
        2
    } // throw before main.
    public static var b: Int64 = 1
}

main() {
    try {
        C();
        ()
    } catch (a: Error) {
        a.printStackTrace()
        print("success")
    }
    return 0
}
