/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 * 
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

import org::{pkgc.f1 as b, pkga.C1, pkgb.*}
import org::{pkgc as org_pkgc, pkga as aa}
import org1::{pkgc as org_pkgc, pkga as aa}
import org2::{pkgc.f1 as b, pkga.C1, pkgb.*}

main() {
    0
}
