/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package UNNAMED

import interoplib.interop.*
import java.lang.*

public struct CangjieStruct {
    public static func foo(param0: JArray<Float32>, param1!: UInt16, param2!: Int32 = 1i32): JArray<Float32> {
        JArray<Float32>(114514i32)
    }
}
