# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[dependencies]

[package]
  cjc-version = "0.41.2"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "dts4284"
  output-type = "static"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option=["${CANGJIE_STDX_PATH}"]

[target.aarch64-unknown-linux-gnu.bin-dependencies]
  path-option=["${CANGJIE_STDX_PATH}"]

[target.cjvm.bin-dependencies]
  path-option=["${CANGJIE_STDX_PATH}"]

[target.x86_64-w64-mingw32.bin-dependencies]
  path-option=["${CANGJIE_STDX_PATH}"]

[target.aarch64-apple-darwin.bin-dependencies]
  path-option=["${CANGJIE_STDX_PATH}"]

[target.x86_64-apple-darwin.bin-dependencies]
  path-option=["${CANGJIE_STDX_PATH}"]