// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package test0

public class C0<T> {
    public prop p0: Int64 {
        get() {
            12
        }
    }
    public static prop p1: Int64 {
        get() {
            12
        }
    }
    public let v0: Int64 = 0
    public static let v1: Int64 = 0
    public func f0(): Unit {}
    public static func f1(): Unit {}
}

public class C1 {
    public prop p0: Int64 {
        get() {
            12
        }
    }
    public static prop p1: Int64 {
        get() {
            12
        }
    }
    public let v0: Int64 = 0
    public static let v1: Int64 = 0
    public func f0(): Unit {}
    public static func f1(): Unit {}
}

public struct S0<T> {
    public prop p0: Int64 {
        get() {
            12
        }
    }
    public static prop p1: Int64 {
        get() {
            12
        }
    }
    public let v0: Int64 = 0
    public static let v1: Int64 = 0
    public func f0(): Unit {}
    public static func f1(): Unit {}
}

public struct S1 {
    public prop p0: Int64 {
        get() {
            12
        }
    }
    public static prop p1: Int64 {
        get() {
            12
        }
    }
    public let v0: Int64 = 0
    public static let v1: Int64 = 0
    public func f0(): Unit {}
    public static func f1(): Unit {}
}
