# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[profile]
experimental = true

[dependencies]
  testing = { path = "./testing" }

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "common_part_debug"
  output-type = "executable"
  override-compile-option = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
