# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.
[repository.cache]
  path = "cache7"
  

[repository.home]
  registry = "https://mirror-centralrepo.devcloud.cn-north-4.huaweicloud.com/artifactory/api/cjpm/cangjie-central-cjpm-test/"
  token = "BaSsic b3SBSfc3DZyXS2NhbDmdqaWU6FSFHVhd2VpMTIjJDEyMzQ1NiE111"