/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 * 
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

// LEVEL: 2
// EXEC: %compiler %import-cangjie-stdx %cmp_opt %stdx-package %f -o %output %cmp_utest_opt
// (not OHOS)RUN-EXEC-PIPE: %run_stdx %output %run_utest_opt %run_args && %cat jloggertest12.txt| compare %f
// (OHOS)RUN-EXEC-PIPE: %run_stdx %output %run_utest_opt %run_args && cat jloggertest12.txt| compare %f
// ASSERT: regex {"time":".*","level":"WARN","msg":"abc","age":2}
// ASSERT: regex {"time":".*","level":"WARN","msg":"","age":2}
// ASSERT: regex {"time":".*","level":"WARN","msg":".*","age":2}
// ASSERT: regex {"time":".*","level":"WARN","msg":"aaaa.*aaaa","age":2}
// ASSERT: regex {"time":".*","level":"WARN","msg":"仓颉鸿蒙","":2}
// ASSERT: regex {"time":".*","level":"WARN","msg":"齾爩麤龗灪龖厵纞虋","":2}
// ASSERT: regex {"time":".*","level":"WARN","msg":"♫♬♪♩✲✳❃❂❁❀","仓颉":2}
// ASSERT: regex {"time":".*","level":"WARN","msg":"cangjietest","123456":2}
// ASSERT: regex {"time":".*","level":"WARN","msg":"cangjietest","123456":""}
// ASSERT: regex {"time":".*","level":"WARN","msg":"cangjietest","123456":"仓颉"}

import std.time.*
import std.io.*
import std.console.Console
import std.fs.*
import std.collection.*
import stdx.encoding.json.stream.*
import stdx.log.*
import stdx.logger.*

@Test
class Test_jsonlogger_warn_12 {
    var fs = File("jloggertest12.txt", ReadWrite)
    var jl12 = JsonLogger(fs)

    public override func afterAll(): Unit {
        jl12.close()
        fs.close()
    }

    @TestCase
    func test_jsonlogger_warn_01(): Unit {
        jl12.warn({=> "abc"}, ("age", 2))
    }

    @TestCase
    func test_jsonlogger_warn_02(): Unit {
        jl12.warn({=> ""}, ("age", 2))
    }

    @TestCase
    func test_jsonlogger_warn_03(): Unit {
        jl12.warn({=> "\0"}, ("age", 2))
    }

    @TestCase
    func test_jsonlogger_warn_04(): Unit {
        let string_long = StringBuilder(r'a', 1000).toString()
        jl12.warn({=> string_long}, ("age", 2))
    }

    @TestCase
    func test_jsonlogger_warn_05(): Unit {
        jl12.warn({=> "仓颉鸿蒙"}, ("", 2))
    }

    @TestCase
    func test_jsonlogger_warn_06(): Unit {
        jl12.warn({=> "齾爩麤龗灪龖厵纞虋"}, ("", 2))
    }

    @TestCase
    func test_jsonlogger_warn_07(): Unit {
        jl12.warn({=> "♫♬♪♩✲✳❃❂❁❀"}, ("仓颉", 2))
    }

    @TestCase
    func test_jsonlogger_warn_08(): Unit {
        jl12.warn({=> "cangjietest"}, ("123456", 2))
    }

    @TestCase
    func test_jsonlogger_warn_09(): Unit {
        jl12.warn({=> "cangjietest"}, ("123456", ""))
    }

    @TestCase
    func test_jsonlogger_warn_10(): Unit {
        jl12.warn({=> "cangjietest"}, ("123456", "仓颉"))
    }
}
