// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

package pkg

public var range1 = 0..10 : 1
public var range2 = 0..5 : 1
public var range3 = 1..10 : 1
public var range4 = 0..10 : 1
public var range5 = 0 + 1..3 + 1
