# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

import os
import subprocess

MAX_PATH = 248
pwd = os.getcwd()

# The generated source file name will not exceed the limit, but the cached file generated by cjc will.
# So the exe product will be succesfully generated, but the cache folder will not,
# and an error about "Failed to create directory" will be raised.
testdirname_len = MAX_PATH - len(pwd) - 6 # 1 character shorter than the length of ".cached" suffix
if testdirname_len < 1:
    print("The path of testing directory is too long to create test files! Try to run this testcase under shorter path.")
    exit()

testdirname = "a" * testdirname_len
if not os.path.exists(testdirname):
	os.makedirs(testdirname)

with open("{}\\a.cj".format(testdirname), "w+") as f:
    f.write("main() {return 0}")
os.chdir(testdirname)
command = "cjc.exe --incremental-compile a.cj"
print(command)
proc = subprocess.run(command, shell=True)
exit(proc.returncode)