# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "1.0.0"
  name = "tree_package_option"
  output-type = "executable"
  version = "1.0.0"

[target.x86_64-unknown-linux-gnu.bin-dependencies]
  package-option = { "binary_dep" = "binary_dep/target/release/binary_dep/binary_dep.cjo" }

[target.x86_64-w64-mingw32.bin-dependencies]
  package-option = { "binary_dep" = "binary_dep/target/release/binary_dep/binary_dep.cjo" }

[target.x86_64-apple-darwin.bin-dependencies]
  package-option = { "binary_dep" = "binary_dep/target/release/binary_dep/binary_dep.cjo" }

[target.aarch64-apple-darwin.bin-dependencies]
  package-option = { "binary_dep" = "binary_dep/target/release/binary_dep/binary_dep.cjo" }
