# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[package]
  cjc-version = "0.60.4"
  name = "mp"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  output-type = "dynamic"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]

[source-set.common]
  src-dir = ["./src/common"]

[source-set.windows]
  src-dir = ["./src/windows"]
  condition.1 = ["feature.arch.x64"]
  condition.2 = ["feature.os.windows"]
  condition.3 = ["feature.env.mingw32"]
  condition.4 = ["feature.arch.sse2"]

[source-set.linux]
  src-dir = ["./src/linux"]
  condition.1 = ["feature.arch.aarch64"]
  condition.2 = ["feature.env.gnu"]
  condition.3 = ["feature.os.linux"]

[source-set.darwin]
  src-dir = ["./src/darwin"]
  condition.1 = ["feature.os.darwin"]
  condition.2 = ["feature.os.kqueue"]