# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.


operators = ['==', '!=', '>', '<', '>=', '<=']
template = '''
/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

/*
  @Assertion:   4.16(4) The syntax of relational expressions are defined as:
                equalityComparisonExpression
                    : comparisonExpression (equalityOperator comparisonExpression)?
                    ;
                comparisonOrTypeExpression
                    : shiftingExpression (comparisonOperator shiftingExpression)?
                    | ...
                    ;
                equalityOperator
                    : '!=' | '=='
                    ;
                comparisonOperator
                : '<' | '>' | '<=' | '>='
                ;
  @Description: Checks that operators {op1} and {op2} together are not permitted.
  @Mode: compileonly
  @Negative: yes
  @Structure: single
  @CompileWarning: no
  @Comment: Auto-generated by gen_infix.py
*/

main() {{
    1 + 2 - 3 * 4 % 5 {op1} {op2} 1 + 2 - 3 * 4 % 5
}}
'''
    
def gen(path : str, counter : int):
  for op1 in operators:
    for op2 in operators:
      if op2 is '-': continue
      counter += 1
      content = template.format(op1=op1, op2=op2)
      with open(path.format(str(counter).zfill(2)), 'w') as file:
        file.write(content)
  return counter
