# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

import random
from os import path

integer_types = ['Int8', 'Int16', 'Int32', 'Int64', 'IntNative', 'UInt8', 'UInt16', 'UInt32', 'UInt64', 'UIntNative']
number_types = integer_types + ['Float16', 'Float32', 'Float64']
other_types = ['String', 'Rune', 'Bool', 'Unit', '(Int8, Int8)', 'Array<Int8>', 'C']
types = number_types + other_types
default_value_map = {'Bool' : 'true', 'Unit' : '()', 'Array<Int8>' : '[1]', 'Rune' : "'1'", 'String' : '"1"', '(Int8, Int8)' : '(1i8, 1i8)', 'C' : 'C(1)'}
ops = ['+', '-', '*', '/', '%', '&', '|', '^', '<<', '>>']

def default_value(ty : str) -> str:
  if ty in integer_types: return '1'
  if 'Float' in ty: return '1.0'
  return default_value_map[ty]

def valid_types(op: str) -> list:
  if op in ['%', '<<', '>>', '|', '&', '^']: return integer_types
  if op in ['&&', '||']: return ['Bool']
  return number_types

dir = path.dirname(path.realpath(__file__))
path = dir + '/test_' + path.basename(dir) + '_{}.cj'
template = '''
/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

/*
  @Assertion:   4.23(24) A compound assignment expression also requires that the two operands be of the same type.
  @Description: %s
  @Mode: %s
  @Negative: %s
  @Structure: single
  @CompileWarning: ignore
  @Comment: Auto-generated by gen.py
*/
%s'''
negative_template = template % ('Checks that the expression a {op}= b is invalid for types {t1} and {t2}.', 'compileonly', 'yes', '''
main() {{
    var v1 : {t1} = {}
    var v2 : {t2} = {}
    v1 {op}= v2
    0
}}
''')
counter = 1

def write_counted(contents : str):
  global counter
  with open(path.format(str(counter).zfill(3)), 'w') as file:
    file.write(contents)
    counter += 1

random.seed(123)
limit = 100
tests = random.sample([negative_template.format(default_value(t1), default_value(t2), t1=t1, t2=t2, op=op)
         for op in ops for t1 in valid_types(op) for t2 in valid_types(op) if t1 != t2], limit) +\
[negative_template.format('true', default_value(t), t1='Bool', t2=t, op=op) for op in ['&&', '||'] for t in types if t != 'Bool']
for test in tests:
  write_counted(test)
