/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This source file is part of the Cangjie project, licensed under Apache-2.0
 * with Runtime Library Exception.
 *
 * See https://cangjie-lang.cn/pages/LICENSE for license information.
 */

package unusedImport.unused_import.pkg08

import {stdx.log.*, stdx.encoding.*}
import {unusedImport.base_pkg1.*, unusedImport.base_pkg2.base_pkg2_inner.*}

abstract class C8 <: Logger {}

var x = StructViaOverLoad()
