# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

[output-roots.a]
path = "./aroot"

[output-roots.b]
path = "./broot"

[output-roots.c]
path = "./croot"

[[packages]]
filters = { include = ["A"] }
package-name = "a"
output-root = "a"

[[packages]]
filters = ["B"]
package-name = "b"
output-root = "b"

[[packages]]
filters = "C"
package-name = "c"
output-root = "c"

[sources.all]
paths = ["test.h"]
