# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
# 
# See https://cangjie-lang.cn/pages/LICENSE for license information.

import json
import subprocess
import os
import shutil
import time
import argparse
from datetime import datetime

android_project_dir_path = os.path.join(os.environ['CANGJIE_TEST'], 'testsuites/HLT/configs/cjnative/android/MyApplication')

def do_cleaning() -> None:
    if os.path.exists(os.path.join(android_project_dir_path, 'app/build')):
        shutil.rmtree(os.path.join(android_project_dir_path, 'app/build'))
    
    if os.path.exists(os.path.join(android_project_dir_path, 'app/libs')):
        shutil.rmtree(os.path.join(android_project_dir_path, 'app/libs'))

    if os.path.exists(os.path.join(android_project_dir_path, 'app/src/main/jniLibs')):
        shutil.rmtree(os.path.join(android_project_dir_path, 'app/src/main/jniLibs'))


def test_case_failed(exit_code: int) -> None:
    print('test case failed.')
    do_cleaning()
    exit(1)

def test_case_passed() -> None:
    print('test case passed.')
    do_cleaning()
    exit(0)


def run_test_case() -> None:
    # build main apk
    print('gradlew assembleDebug')
    result = subprocess.run(['bash', os.path.join(android_project_dir_path, 'gradlew'), 'assembleDebug'], cwd=android_project_dir_path)
    if result.returncode != 0:
        test_case_failed(result.returncode)

    # build test apk
    print('gradlew assembleAndroidTest')
    result = subprocess.run(['bash', os.path.join(android_project_dir_path, 'gradlew'), 'assembleAndroidTest'], cwd=android_project_dir_path)
    if result.returncode != 0:
        test_case_failed(result.returncode)

    # installing apk
    device_id = os.environ.get('device', 'emulator-5554')
    apk_file_path = os.path.join(android_project_dir_path, 'app/build/outputs/apk/debug/app-debug.apk')
    print(f'adb -s {device_id} install -r {apk_file_path}')
    result = subprocess.run(['adb', '-s', device_id, 'install', '-r', apk_file_path])
    if result.returncode != 0:
        test_case_failed(result.returncode)
    
    # installing test apk
    android_test_apk_file_path = os.path.join(android_project_dir_path, 'app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk')
    print(f'adb -s {device_id} install -r {android_test_apk_file_path}')
    result = subprocess.run(['adb', '-s', device_id, 'install', '-r', android_test_apk_file_path])
    if result.returncode != 0:
        test_case_failed(result.returncode)
    
    # run tests
    test_cmd = ['adb', '-s', device_id, 'shell', 'am', 'instrument', '-w', '-e', 'junitXml', '/sdcard/report.xml', 'com.example.myapplication.test/androidx.test.runner.AndroidJUnitRunner']
    print(' '.join(test_cmd))
    result = subprocess.run(test_cmd, capture_output=True, text=True, encoding='utf-8')
    stdout = result.stdout
    print(result.stdout)
    print(result.stderr)
    if '\n\nOK (' in stdout:
        # test case passed
        test_case_passed()
    else:
        # test case failed
        test_case_failed(1)

def main() -> None:
    run_test_case()

def clear_android_studio_project(project_dir_path: str) -> None:
    shutil.rmtree(os.path.join(project_dir_path, '.cache'))

def build_java() -> None:
    # temp working dir for current test case generated by cangjie test framework.
    test_case_dir_path = os.getcwd()
    java_source_root_dir_name = args.java_source_root
    # dir containing test case's java source files.
    java_source_root_dir_path = os.path.join(test_case_dir_path, java_source_root_dir_name)
    # dir containing java source files.
    android_java_dir_path = os.path.join(android_project_dir_path, 'app/src/main/java')
    hello_dir_path = os.path.join(android_java_dir_path, 'com/example/myapplication')
    shutil.rmtree(hello_dir_path)
    os.makedirs(hello_dir_path, exist_ok=True)
    shutil.copyfile(os.path.join(test_case_dir_path, 'Logger.java'), os.path.join(hello_dir_path, 'Logger.java'))
    target = os.path.join(android_java_dir_path, java_source_root_dir_name)
    # clear all
    for file_name in os.listdir(target):
        if file_name.endswith('.java') or file_name.endswith('.class'):
            os.remove(os.path.join(target, file_name))
    # copying test case java source files to android studio project.
    if os.path.exists(java_source_root_dir_path):
        shutil.copytree(java_source_root_dir_path, target, dirs_exist_ok=True)
        # compile java source files using javac.
        result = subprocess.run(['javac', f'{java_source_root_dir_path}/*.java'], cwd=java_source_root_dir_path, capture_output=True, text=True, encoding='utf-8')
    
    # first, clear jniLibs.
    jni_libs_dir_path = os.path.join(android_project_dir_path, 'app/src/main/jniLibs/arm64-v8a')
    if os.path.exists(jni_libs_dir_path):
        shutil.rmtree(jni_libs_dir_path)
    os.makedirs(jni_libs_dir_path, exist_ok=True)

    # copying Cangjie dynamic library to jniLibs.
    cangjie_dylib_file_path = os.path.join(test_case_dir_path, 'libUNNAMED.so')
    shutil.copyfile(cangjie_dylib_file_path, os.path.join(jni_libs_dir_path, 'libUNNAMED.so'))

    # copying necessary dynamic libraries from Cangjie SDK.
    cangjie_runtime_lib_dir_path = os.path.join(os.environ['CANGJIE_HOME'], 'runtime/lib/linux_android_aarch64_cjnative')
    for file_name in os.listdir(cangjie_runtime_lib_dir_path):
        shutil.copyfile(os.path.join(cangjie_runtime_lib_dir_path, file_name), os.path.join(jni_libs_dir_path, file_name))

    # copying libc++_shared.so from Android NDK.
    ndk_dir_path = os.path.join(os.environ['OHOS_ROOT'], 'llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so')
    shutil.copyfile(ndk_dir_path, os.path.join(jni_libs_dir_path, 'libc++_shared.so'))

    # copying instrumented test source file.
    test_entry_file_path = os.path.join(test_case_dir_path, args.test_entry)
    instrumented_test_dir_path = os.path.join(android_project_dir_path, 'app/src/androidTest/java/com/example/myapplication')
    shutil.copyfile(test_entry_file_path, os.path.join(instrumented_test_dir_path, args.test_entry))

    # copying library-loader.jar to app/libs.
    # this path is configured in app/build.gradle.kts
    libs_dir_path = os.path.join(android_project_dir_path, 'app/libs')
    if os.path.exists(libs_dir_path):
        shutil.rmtree(libs_dir_path)
    os.makedirs(libs_dir_path, exist_ok=True)
    shutil.copyfile(os.path.join(os.environ['CANGJIE_HOME'], 'lib', 'library-loader.jar'), os.path.join(libs_dir_path, 'library-loader.jar'))

def parse_command_line_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument('--test-entry', dest='test_entry', type=str)
    parser.add_argument('--main-entry', dest='main_entry', type=str)
    parser.add_argument('--java-source-root', dest='java_source_root', type=str)
    parser.add_argument('--cangjie-source-root', dest='cangjie_source_root', type=str)
    parser.add_argument('--device-id', dest='device_id', type=str)
    return parser.parse_args()
    
    
if __name__ == '__main__':
    args = parse_command_line_arguments()
    build_java()
    main()
