# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# This source file is part of the Cangjie project, licensed under Apache-2.0
# with Runtime Library Exception.
#
# See https://cangjie-lang.cn/pages/LICENSE for license information.

#!/bin/bash

set -xe

# copy Logger.java & logger.cj to test case dir.
TEST_CASE_PATH=$PWD
cp "$CANGJIE_TEST/testsuites/HLT/compiler/cjnative/FFI/jffi/android/util/logger.cj" "$TEST_CASE_PATH/logger.cj"
cp "$CANGJIE_TEST/testsuites/HLT/compiler/cjnative/FFI/jffi/android/util/Logger.java" "$TEST_CASE_PATH/Logger.java"

# reset UNNAMED dir in android project.
ANDROID_PROJ_PATH="$CANGJIE_TEST/testsuites/HLT/configs/cjnative/android/MyApplication"
rm -rf "$ANDROID_PROJ_PATH/app/src/main/java/UNNAMED"
mkdir -p "$ANDROID_PROJ_PATH/app/src/main/java/UNNAMED"

# copy output java mirror generated by cjc to android project, if there's any.
if [ -e "$TEST_CASE_PATH"/java-gen ]; then
	cp "$TEST_CASE_PATH"/java-gen/* "$ANDROID_PROJ_PATH/app/src/main/java/UNNAMED"
fi

# reset app/src/main/java/com/example/myapplication dir in android project.
rm -rf "$ANDROID_PROJ_PATH/app/src/main/java/com/example/myapplication"
mkdir -p "$ANDROID_PROJ_PATH/app/src/main/java/com/example/myapplication"

# copy Logger.java to app/src/main/java/com/example/myapplication
cp "$TEST_CASE_PATH/Logger.java" "$ANDROID_PROJ_PATH/app/src/main/java/com/example/myapplication/Logger.java"

UNITTEST_FILE="MainInstrumentedTest.java"

# clear all .java & .class files previously copied to app/src/main/java/com.
rm -rf "$ANDROID_PROJ_PATH"/app/src/main/java/com/*.java
rm -rf "$ANDROID_PROJ_PATH"/app/src/main/java/com/*.class

# copying test case java source files to android studio project.
cp -rf "$TEST_CASE_PATH/com" "$ANDROID_PROJ_PATH/app/src/main/java"

# first, clear jniLibs.
JNI_LIB_PATH="$ANDROID_PROJ_PATH/app/src/main/jniLibs/arm64-v8a"
rm -rf "$JNI_LIB_PATH"
mkdir -p "$JNI_LIB_PATH"

# copying Cangjie dynamic library to jniLibs.
cp "$TEST_CASE_PATH/libUNNAMED.so" "$JNI_LIB_PATH/libUNNAMED.so"
# copying necessary dynamic libraries from Cangjie SDK.
cp "$CANGJIE_HOME/runtime/lib/$1"/* "$JNI_LIB_PATH"

# copying libc++_shared.so from Android NDK.
cp "$OHOS_ROOT/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/$2/libc++_shared.so" "$JNI_LIB_PATH/libc++_shared.so"

# copying instrumented test source file.
rm -rf "$ANDROID_PROJ_PATH/app/src/androidTest/java/com/example/myapplication"
mkdir -p "$ANDROID_PROJ_PATH/app/src/androidTest/java/com/example/myapplication"
cp "$UNITTEST_FILE" "$ANDROID_PROJ_PATH/app/src/androidTest/java/com/example/myapplication/$UNITTEST_FILE"

# copying library-loader.jar to app/libs.
# this path is configured in app/build.gradle.kts
rm -rf "$ANDROID_PROJ_PATH/app/libs"
mkdir -p "$ANDROID_PROJ_PATH/app/libs"
cp "$CANGJIE_HOME/lib/library-loader.jar" "$ANDROID_PROJ_PATH/app/libs/library-loader.jar"

cd "$ANDROID_PROJ_PATH"

# build APKs.
./gradlew assembleDebug
./gradlew assembleAndroidTest

if [ -z "${DEVICE_ID}" ]; then
	DEVICE_ID="emulator-5554"
fi

# installing main APK.
adb -s "${DEVICE_ID}" install -r "$ANDROID_PROJ_PATH/app/build/outputs/apk/debug/app-debug.apk"

# installing test APK.
adb -s "${DEVICE_ID}" install -r "$ANDROID_PROJ_PATH/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"

# run tests.
adb -s "$DEVICE_ID" shell am instrument -w -e junitXml "/sdcard/report.xml" "com.example.myapplication.test/androidx.test.runner.AndroidJUnitRunner" 2>&1 > result.txt

# do cleaning.
rm -rf "$ANDROID_PROJ_PATH/app/build"
rm -rf "$ANDROID_PROJ_PATH/app/libs"
rm -rf "$ANDROID_PROJ_PATH/app/src/main/jniLibs"

cat result.txt

if grep -q "OK (" result.txt; then
    exit 0
else
    exit 1
fi
